### ISSUE TITLE
About some issues of pytorch version and loss stagnation

### ISSUE THREAD

**Issue by momo1986** [Phoveran/vp-for-adversarial-robustness#3]
Thanks for sharing.

It is really an interesting work.

I have two questions:
1. What is the suitable pytorch version to reproduce the result?
2. To get a robust visual prompt before NN, I could just run the cifar10_pretrain.py and then gen_prompt.py with the default parameters, isn't it? However, I find that the input data is lousy that the loss does not degrade.
![image](https://user-images.githubusercontent.com/34225874/218919059-347c8ed3-c956-4e3a-8cd6-01e174f3e71c.png)

I wish you are all godd.

Thanks & regards!
Momo

**Comment by Phoveran** [comment]
Thanks for your interest in our work!
1. Python 3.9+ with pytorch 1.12.0
2. You may need to config the path in cfg.py at first

**Comment by jS5t3r** [comment]
ReadMe is added. Checkout the `requirements2.txt` or `environment.yml` for installing a conda environment. Code usage is described in the readme.

**Comment by Phoveran** [comment]
Close due to long-time non-activity. Please reopen if needed.
