### ISSUE TITLE
Loss give NaN Value

### ISSUE THREAD

**Issue by Mikael17125** [Phoveran/vp-for-adversarial-robustness#4]
I run gen_prompt.py and change the batch size, it give me NaN loss, but if it's original batch_size the loss is normal.

![image](https://github.com/Phoveran/vp-for-adversarial-robustness/assets/27775792/312ff518-367b-40e0-b7d7-9d238d4eaffd)

**Comment by Phoveran** [comment]
With different batch sizes, adjust your hyperparameters such as lr. Note that we do not guarantee convergence over hyperparameters other than we have chosen.

**Comment by Mikael17125** [comment]
Has the experiment already been applied to a larger dataset, such as ImageNet, which has larger classes?
